<?php

namespace Database\Seeders;

use App\Models\Manga;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class MangaTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {

$mangalist = [
    ['titolo'=>'One Piece','autore'=>'Eiichiro Oda','descrizione'=>'Monkey D. Luffy, ragazzo che mangia il frutto del diavolo Gom Gom, parte dal villaggio di Foosha per diventare il Re dei Pirati. Incontra compagni unici, esplora isole misteriose, affronta la Marina e potenti pirati mentre costruisce la sua ciurma, determinato a trovare il leggendario tesoro “One Piece”.','url_copertina'=>'https://onepiece.fandom.com/wiki/File:Volume_1.png','editore'=>'Shueisha','status'=>'in corso','numero_volumi'=>105,'data_inizio'=>'1997-07-22','valutazione'=>9.7],
    ['titolo'=>'Dragon Ball','autore'=>'Akira Toriyama','descrizione'=>'Goku, un giovane con la coda di scimmia, incontra Bulma e inizia una ricerca per raccogliere le sette Sfere del Drago, oggetti magici che esaudiscono ogni desiderio. Durante il viaggio affronta nemici pericolosi, si allena, fa nuove amicizie e scopre il mondo dei combattimenti marziali.','url_copertina'=>'https://upload.wikimedia.org/wikipedia/en/7/7b/Dragon_Ball_vol_1.jpg','editore'=>'Shueisha','status'=>'completato','numero_volumi'=>42,'data_inizio'=>'1984-11-20','valutazione'=>9.3],
    ['titolo'=>'Attack on Titan','autore'=>'Hajime Isayama','descrizione'=>'In un mondo dove l’umanità è quasi estinta a causa dei giganti “Titani”, Eren Jaeger giura vendetta dopo che la sua città viene distrutta. Si arruola nell’esercito e, insieme ad amici come Mikasa e Armin, scopre verità sconvolgenti sulla loro origine e sulle mura che li proteggono.','url_copertina'=>'https://upload.wikimedia.org/wikipedia/en/6/67/Attack_on_Titan_volume_1_cover.jpg','editore'=>'Kodansha','status'=>'completato','numero_volumi'=>34,'data_inizio'=>'2009-09-09','valutazione'=>9.1],
    ['titolo'=>'Fruits Basket','autore'=>'Natsuki Takaya','descrizione'=>'Tohru Honda, orfana e ottimista, scopre di vivere con la famiglia Soma, maledetta da antiche creature zodiacali: quando abbracciano chi li ha feriti, si trasformano nell’animale corrispondente. Aiuta ogni membro della famiglia ad affrontare traumi personali, guarire e accettarsi per ciò che sono.','url_copertina'=>'https://upload.wikimedia.org/wikipedia/en/5/54/Fruits_Basket_vol_01.jpg','editore'=>'Hakusensha','status'=>'completato','numero_volumi'=>23,'data_inizio'=>'1998-07-19','valutazione'=>8.9],
    ['titolo'=>'Sakamoto Days','autore'=>'Yuto Suzuki','descrizione'=>'Tadaomi Sakamoto, ex sicario temuto, ha lasciato una vita violenta per gestire un tranquillo minimarket insieme alla moglie. Ma quando il suo passato lo raggiunge, deve proteggere i suoi cari affrontando assassini e vecchie rivalità, mescolando azione intensa, gag comiche e momenti teneri.','url_copertina'=>'https://read.sakurajima.cloud/covers/sakamoto_days_volume_1.jpg','editore'=>'Shueisha','status'=>'in corso','numero_volumi'=>21,'data_inizio'=>'2020-11-11','valutazione'=>8.5],
    ['titolo'=>'Naruto','autore'=>'Masashi Kishimoto','descrizione'=>'Naruto Uzumaki, giovane ninja ostracizzato perché ospita la Volpe a Nove Code, sogna di diventare Hokage e guadagnarsi l’accettazione del villaggio. Durante gli esami e le missioni sviluppa amicizie profonde, affronta nemici potenti e scopre segreti sul suo destino e sulla bestia sigillata dentro di lui.','url_copertina'=>'https://artsandculture.google.com/asset/NARUTO-the-cover-of-vol-1-c-masashi-sugumoto-scott-shueisha','editore'=>'Shueisha','status'=>'completato','numero_volumi'=>72,'data_inizio'=>'1999-09-21','valutazione'=>9.2],
    ['titolo'=>'Bleach','autore'=>'Tite Kubo','descrizione'=>'Ichigo Kurosaki, studente con poteri da mietitore di anime, ottiene la capacità di vedere i fantasmi. Assorbe i poteri da una Shinigami e diventa lei stesso un mietitore. Combatte spiriti maligni chiamati Hollows, protegge il mondo umano e scopre misteri legati alla sua famiglia e al mondo spirituale.','url_copertina'=>'https://manga-news.com/__data/assets/image/0008/123456/bleach_vol1.jpg','editore'=>'Shueisha','status'=>'completato','numero_volumi'=>74,'data_inizio'=>'2001-08-07','valutazione'=>9.0],
    ['titolo'=>'My Hero Academia','autore'=>'Kohei Horikoshi','descrizione'=>'In un mondo dove l’80% della popolazione ha superpoteri (Quirk), Izuku “Deku” Midoriya nasce senza. Nonostante tutto, sogna di diventare un eroe. Dopo un incontro con All Might, eredita il suo potere e si iscrive alla U.A. Academy, dove affronta sfide e impara cosa significa essere eroe.','url_copertina'=>'https://upload.wikimedia.org/wikipedia/en/5/5a/My_Hero_Academia_Volume_1.jpg','editore'=>'Shueisha','status'=>'in corso','numero_volumi'=>37,'data_inizio'=>'2014-07-07','valutazione'=>8.8],
    ['titolo'=>'Jujutsu Kaisen','autore'=>'Gege Akutami','descrizione'=>'Yuji Itadori, studente dotato di forza sovrumana, ingerisce un dito maledetto per salvare gli amici da una maledizione. Diventa ospite di Sukuna, un potente demone, e inizia a frequentare l’istituto Jujutsu per imparare a combattere maledizioni e proteggere gli innocenti.','url_copertina'=>'https://upload.wikimedia.org/wikipedia/en/d/da/Jujutsu_Kaisen_volume_1_cover.jpg','editore'=>'Shueisha','status'=>'in corso','numero_volumi'=>23,'data_inizio'=>'2018-03-05','valutazione'=>8.7],
    ['titolo'=>'Demon Slayer','autore'=>'Koyoharu Gotouge','descrizione'=>'Tanjiro Kamado torna a casa e trova la famiglia sterminata dai demoni, tranne la sorella Nezuko, trasformata a sua volta. Diventa cacciatore di demoni per liberarla e vendicarli, affrontando creature spaventose e addestrandosi per diventare forte.','url_copertina'=>'https://upload.wikimedia.org/wikipedia/en/0/0b/Demon_Slayer_volume_1_cover.jpg','editore'=>'Shueisha','status'=>'completato','numero_volumi'=>23,'data_inizio'=>'2016-02-15','valutazione'=>9.1],
    ['titolo'=>'Hunter x Hunter','autore'=>'Yoshihiro Togashi','descrizione'=>'Gon Freecss scopre che il padre, che credeva morto, è un famoso Hunter. Decide di seguirlo diventando lui stesso un Hunter: affronta esami pericolosi, incontra amici come Killua, Leorio e Kurapika, e scopre un mondo pieno di creature, misteri e temibili nemici.','url_copertina'=>'https://upload.wikimedia.org/wikipedia/en/4/4c/Hunter_x_Hunter_vol1.jpg','editore'=>'Shueisha','status'=>'in corso','numero_volumi'=>36,'data_inizio'=>'1998-03-16','valutazione'=>9.0],
    ['titolo'=>'Fullmetal Alchemist','autore'=>'Hiromu Arakawa','descrizione'=>'I fratelli Edward e Alphonse Elric praticano alchimia proibita per riportare in vita la madre, ma subiscono conseguenze drammatiche: Edward perde un braccio e una gamba, Alphonse perde il corpo. Inizia un viaggio per trovare la Pietra Filosofale e ripristinare ciò che hanno perso.','url_copertina'=>'https://upload.wikimedia.org/wikipedia/en/4/4e/Fullmetal_Alchemist_Volume_1.jpg','editore'=>'Square Enix','status'=>'completato','numero_volumi'=>27,'data_inizio'=>'2001-07-12','valutazione'=>9.2],
    ['titolo'=>'Death Note','autore'=>'Tsugumi Ohba & Takeshi Obata','descrizione'=>'Light Yagami trova un quaderno sovrannaturale: chi vi scrive il nome muore. Decide di usarlo per eliminare criminali e creare un nuovo mondo perfetto. Inizia un duello psicologico contro L, detective geniale, in una catena di inganni e tensione costante.','url_copertina'=>'https://upload.wikimedia.org/wikipedia/en/6/6f/Death_Note_Vol_01.jpg','editore'=>'Shueisha','status'=>'completato','numero_volumi'=>12,'data_inizio'=>'2003-12-01','valutazione'=>9.0],
    ['titolo'=>'Tokyo Ghoul','autore'=>'Sui Ishida','descrizione'=>'Ken Kaneki ha un appuntamento che lo porta a diventare metà umano e metà ghoul, creature che si nutrono di carne umana. Lotta per mantenere la propria umanità e trovare un equilibrio tra le due nature, scontrandosi con società oscure e sofferenza.','url_copertina'=>'https://upload.wikimedia.org/wikipedia/en/thumb/1/1c/Tokyo_Ghoul_volume_1.jpg','editore'=>'Shueisha','status'=>'completato','numero_volumi'=>14,'data_inizio'=>'2011-09-08','valutazione'=>8.4],
    ['titolo'=>'Fairy Tail','autore'=>'Hiro Mashima','descrizione'=>'Lucy Heartfilia sogna di unirsi alla gilda Fairy Tail. Incontra Natsu e Happy, maghi avventurosi, e partecipa a missioni pericolose. La serie combina combattimenti magici, amicizia, avventure epiche e crescita personale.','url_copertina'=>'https://upload.wikimedia.org/wikipedia/en/3/3b/Fairy_Tail_Volume_1.jpg','editore'=>'Kodansha','status'=>'completato','numero_volumi'=>63,'data_inizio'=>'2006-08-02','valutazione'=>8.3],
    ['titolo'=>'Black Clover','autore'=>'Yūki Tabata','descrizione'=>'Asta e Yuno sono orfani cresciuti insieme in un villaggio, entrambi ambiscono a diventare Imperatore Mago. Yuno ottiene poteri magici straordinari, mentre Asta rimane privo di Quattro ma acquisisce capacità anti-magia e si impegna per dimostrare il suo valore.','url_copertina'=>'https://upload.wikimedia.org/wikipedia/en/8/8f/Black_Clover_Volume_1.jpg','editore'=>'Shueisha','status'=>'in corso','numero_volumi'=>35,'data_inizio'=>'2015-02-16','valutazione'=>8.2],
    ['titolo'=>'Boarding School Juliet','autore'=>'Yōsuke Kaneda','descrizione'=>'Juliet Persia e Romeo Inuzuka studiano in due famiglie rivali della Dahlia Academy. Nonostante l’odio tra le famiglie, si innamorano segretamente e cercano di mantenere viva la loro storia, tra scandali, amici, rivalità e sfide scolastiche.','url_copertina'=>'https://upload.wikimedia.org/wikipedia/en/7/78/Boarding_School_Juliet_vol1.jpg','editore'=>'Kodansha','status'=>'completato','numero_volumi'=>10,'data_inizio'=>'2015-03-13','valutazione'=>7.5],
    ['titolo'=>'Vinland Saga','autore'=>'Makoto Yukimura','descrizione'=>'Ambientata nell’epoca dei vichinghi, segue Thorfinn, ragazzo figlio di un guerriero, mentre cresce con il desiderio di vendetta per suo padre assassinato. Si unisce a guerrieri leggendari, impara la brutalità della guerra e riflette sul vero significato dell’onore e del perdono.','url_copertina'=>'https://upload.wikimedia.org/wikipedia/en/1/1d/Vinland_Saga_vol1.jpg','editore'=>'Kodansha','status'=>'in corso','numero_volumi'=>24,'data_inizio'=>'2005-04-14','valutazione'=>9.3],
    ['titolo'=>'Claymore','autore'=>'Norihiro Yagi','descrizione'=>'In un mondo infestato da Yoma, demoni che si nutrono di umani, l’organizzazione Claymore addestra guerriere metà umane metà demoni per combatterli. Clare, una guerriera esperta, affronta missioni pericolose mentre cerca la verità sulla sua esistenza e il suo passato.','url_copertina'=>'https://upload.wikimedia.org/wikipedia/en/a/ad/Claymore_Volume_1.jpg','editore'=>'Shueisha','status'=>'completato','numero_volumi'=>27,'data_inizio'=>'2001-05-09','valutazione'=>8.6],
    ['titolo'=>'Kingdom','autore'=>'Yasuhisa Hara','descrizione'=>'Ambientato durante gli Stati Combattenti in Cina, segue Xin, un orfano con il sogno di diventare grande generale. Combatte in battaglie epiche, crea alleanze e scala i ranghi militari, sperimentando la crudeltà e la strategia della guerra.','url_copertina'=>'https://upload.wikimedia.org/wikipedia/en/2/29/Kingdom_vol1.jpg','editore'=>'Shueisha','status'=>'in corso','numero_volumi'=>71,'data_inizio'=>'2006-01-26','valutazione'=>8.9],
];



        foreach ($mangalist as $manga) {
            $newManga = new Manga();

            $newManga->titolo = $manga['titolo'];
            $newManga->autore = $manga['autore'];
            $newManga->descrizione = $manga['descrizione'];
            $newManga->url_copertina = $manga['url_copertina'];
            $newManga->editore = $manga['editore'];
            $newManga->status = $manga['status'];
            $newManga->numero_volumi = $manga['numero_volumi'];
            $newManga->data_inizio = $manga['data_inizio'];
            $newManga->valutazione = $manga['valutazione'];

            $newManga->save();
        }

    }
}
